# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # creates images
    - run: docker-compose -f docker-compose-build.yaml build --parallel

    # tags images to docker
    - run: docker tag udagram-frontend:local ampire90/udagram-frontend:v8
    - run: docker tag udagram-api-user ampire90/udagram-api-user:v10
    - run: docker tag udagram-api-feed ampire90/udagram-api-feed:v11
    - run: docker tag reverseproxy ampire90/reverseproxy:v3

    # logins to DockerHub
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

    # pushes to DockerHub
    - run: docker push ampire90/udagram-frontend:v8
    - run: docker push ampire90/udagram-api-user:v10
    - run: docker push ampire90/udagram-api-feed:v11
    - run: docker push ampire90/reverseproxy:v3